# coding: utf-8

"""
    AccuTraining OpenAPI 3

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.actionassignment_api import ActionassignmentApi  # noqa: E501
from openapi_client.rest import ApiException


class TestActionassignmentApi(unittest.TestCase):
    """ActionassignmentApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.actionassignment_api.ActionassignmentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_actionassignment_delete(self):
        """Test case for actionassignment_delete

        Remove an action item from an action plan  # noqa: E501
        """
        pass

    def test_actionassignment_get(self):
        """Test case for actionassignment_get

        Search and view details of an action item assigned to a user  # noqa: E501
        """
        pass

    def test_actionassignment_list(self):
        """Test case for actionassignment_list

        View a list of action items in a user's plan  # noqa: E501
        """
        pass

    def test_actionassignment_listhistory(self):
        """Test case for actionassignment_listhistory

        View the history of an action item assigned to a user  # noqa: E501
        """
        pass

    def test_actionassignment_listmine(self):
        """Test case for actionassignment_listmine

        List public action assignments assigned to the logged user  # noqa: E501
        """
        pass

    def test_actionassignment_listpublichistory(self):
        """Test case for actionassignment_listpublichistory

        List public action assignment history  # noqa: E501
        """
        pass

    def test_actionassignment_markcomplete(self):
        """Test case for actionassignment_markcomplete

        Bulk complete action items  # noqa: E501
        """
        pass

    def test_actionassignment_save(self):
        """Test case for actionassignment_save

        Add an action item to a user's action plan  # noqa: E501
        """
        pass

    def test_actionassignment_savehistory(self):
        """Test case for actionassignment_savehistory

        Update an action item assigned to a user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
