/*
 * AccuTraining OpenAPI 3
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CaptchaApi
 */
@Ignore
public class CaptchaApiTest {

    private final CaptchaApi api = new CaptchaApi();

    
    /**
     * Gets a captcha challenge that the user must complete to do certain requests.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void captchaGetchallengeTest() throws ApiException {
        api.captchaGetchallenge();

        // TODO: test validations
    }
    
    /**
     * Gets a captcha image that the user must complete to do certain requests.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void captchaGetimageTest() throws ApiException {
        String captchatoken = null;
        api.captchaGetimage(captchatoken);

        // TODO: test validations
    }
    
}
