=begin comment

AccuCampus OpenAPI 3

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::BeaconApi');

my $api = WWW::OpenAPIClient::BeaconApi->new();
isa_ok($api, 'WWW::OpenAPIClient::BeaconApi');

#
# beacon_delete test
#
{
    my $id = undef; # replace NULL with a proper value
    my $body = undef; # replace NULL with a proper value
    my $result = $api->beacon_delete(id => $id, body => $body);
}

#
# beacon_disable test
#
{
    my $result = $api->beacon_disable();
}

#
# beacon_get test
#
{
    my $id = undef; # replace NULL with a proper value
    my $result = $api->beacon_get(id => $id);
}

#
# beacon_getlocations test
#
{
    my $beacons = undef; # replace NULL with a proper value
    my $result = $api->beacon_getlocations(beacons => $beacons);
}

#
# beacon_getstationlocation test
#
{
    my $station = undef; # replace NULL with a proper value
    my $location = undef; # replace NULL with a proper value
    my $result = $api->beacon_getstationlocation(station => $station, location => $location);
}

#
# beacon_getuuid test
#
{
    my $result = $api->beacon_getuuid();
}

#
# beacon_list test
#
{
    my $from = undef; # replace NULL with a proper value
    my $count = undef; # replace NULL with a proper value
    my $result = $api->beacon_list(from => $from, count => $count);
}

#
# beacon_listprofiles test
#
{
    my $result = $api->beacon_listprofiles();
}

#
# beacon_resetuuid test
#
{
    my $result = $api->beacon_resetuuid();
}

#
# beacon_save test
#
{
    my $id = undef; # replace NULL with a proper value
    my $unknown_base_type = undef; # replace NULL with a proper value
    my $result = $api->beacon_save(id => $id, unknown_base_type => $unknown_base_type);
}

#
# beacon_scanlocations test
#
{
    my $beacons = undef; # replace NULL with a proper value
    my $result = $api->beacon_scanlocations(beacons => $beacons);
}

#
# beacon_setuuid test
#
{
    my $id = undef; # replace NULL with a proper value
    my $result = $api->beacon_setuuid(id => $id);
}

#
# beacon_silentregions test
#
{
    my $result = $api->beacon_silentregions();
}

#
# beacon_silentsignin test
#
{
    my $uuid = undef; # replace NULL with a proper value
    my $result = $api->beacon_silentsignin(uuid => $uuid);
}

#
# beacon_silentsignout test
#
{
    my $uuid = undef; # replace NULL with a proper value
    my $result = $api->beacon_silentsignout(uuid => $uuid);
}


1;
