/*
 * AccuCampus OpenAPI 3
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.UNKNOWN_BASE_TYPE;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ActionitemApi
 */
@Ignore
public class ActionitemApiTest {

    private final ActionitemApi api = new ActionitemApi();

    
    /**
     * Delete an action item
     *
     * Allows the user to delete an action item.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void actionitemDeleteTest() throws ApiException {
        UUID id = null;
        oas_any_type_not_mapped body = null;
        api.actionitemDelete(id, body);

        // TODO: test validations
    }
    
    /**
     * Search and view details of an action item
     *
     * Allows the user to view an individual action item and its details.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void actionitemGetTest() throws ApiException {
        UUID id = null;
        api.actionitemGet(id);

        // TODO: test validations
    }
    
    /**
     * View a list of action items
     *
     * Allows the user to view a list of action items
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void actionitemListTest() throws ApiException {
        Integer from = null;
        Integer count = null;
        api.actionitemList(from, count);

        // TODO: test validations
    }
    
    /**
     * Create or edit an action item
     *
     * Allows the user to edit an action item.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void actionitemSaveTest() throws ApiException {
        UUID id = null;
        UNKNOWN_BASE_TYPE UNKNOWN_BASE_TYPE = null;
        api.actionitemSave(id, UNKNOWN_BASE_TYPE);

        // TODO: test validations
    }
    
}
