/*
 * AccuCampus OpenAPI 3
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VirtuallineApi
 */
@Ignore
public class VirtuallineApiTest {

    private final VirtuallineApi api = new VirtuallineApi();

    
    /**
     * Add myself to a waiting line
     *
     * Allows the user to add themselves to a waiting line from the AccuCampus mobile app.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void virtuallineAddmyselfTest() throws ApiException {
        UUID waitinglineid = null;
        api.virtuallineAddmyself(waitinglineid);

        // TODO: test validations
    }
    
    /**
     * Lists waiting lines that have remote access enabled
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void virtuallineListTest() throws ApiException {
        api.virtuallineList();

        // TODO: test validations
    }
    
    /**
     * Remove myself from a waiting line
     *
     * Allows the user to remove themselves from a waiting line in the AccuCampus mobile app.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void virtuallineRemovemyselfTest() throws ApiException {
        api.virtuallineRemovemyself();

        // TODO: test validations
    }
    
}
