# coding: utf-8

"""
    AccuClub OpenAPI 3

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.creditplan_api import CreditplanApi  # noqa: E501
from openapi_client.rest import ApiException


class TestCreditplanApi(unittest.TestCase):
    """CreditplanApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.creditplan_api.CreditplanApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_creditplan_delete(self):
        """Test case for creditplan_delete

        Deletes a credit plan  # noqa: E501
        """
        pass

    def test_creditplan_get(self):
        """Test case for creditplan_get

        Gets a credit plan  # noqa: E501
        """
        pass

    def test_creditplan_list(self):
        """Test case for creditplan_list

        Gets the credit plans available  # noqa: E501
        """
        pass

    def test_creditplan_save(self):
        """Test case for creditplan_save

        Saves a credit plan  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
