FROM openapitools/openapi-generator-cli
MAINTAINER Heba Nassereddeen 
WORKDIR /
COPY script.sh script.sh
COPY cl-downloader.sh cl-downloader.sh
COPY docker-entrypoint.sh docker-entrypoint.sh
CMD ["bash", "script.sh"]





