from __future__ import absolute_import

# flake8: noqa

# import apis into api package
from openapi_client.api.general_api import GeneralApi
from openapi_client.api.actionassignment_api import ActionassignmentApi
from openapi_client.api.actionitem_api import ActionitemApi
from openapi_client.api.actionlog_api import ActionlogApi
from openapi_client.api.actionpack_api import ActionpackApi
from openapi_client.api.actiontype_api import ActiontypeApi
from openapi_client.api.adhocquery_api import AdhocqueryApi
from openapi_client.api.adhocreports_api import AdhocreportsApi
from openapi_client.api.advancedstation_api import AdvancedstationApi
from openapi_client.api.advrole_api import AdvroleApi
from openapi_client.api.advroles_api import AdvrolesApi
from openapi_client.api.appointment_api import AppointmentApi
from openapi_client.api.appshare_api import AppshareApi
from openapi_client.api.attendancelog_api import AttendancelogApi
from openapi_client.api.attendancelogcomment_api import AttendancelogcommentApi
from openapi_client.api.attendancerestriction_api import AttendancerestrictionApi
from openapi_client.api.beacon_api import BeaconApi
from openapi_client.api.bgjob_api import BgjobApi
from openapi_client.api.captcha_api import CaptchaApi
from openapi_client.api.client_api import ClientApi
from openapi_client.api.community_api import CommunityApi
from openapi_client.api.compasscategory_api import CompasscategoryApi
from openapi_client.api.compassservice_api import CompassserviceApi
from openapi_client.api.computerlab_api import ComputerlabApi
from openapi_client.api.deadendrecording_api import DeadendrecordingApi
from openapi_client.api.department_api import DepartmentApi
from openapi_client.api.easylogin_api import EasyloginApi
from openapi_client.api.event_api import EventApi
from openapi_client.api.eventreg_api import EventregApi
from openapi_client.api.export_api import ExportApi
from openapi_client.api.feature_api import FeatureApi
from openapi_client.api.holiday_api import HolidayApi
from openapi_client.api.import_api import ImportApi
from openapi_client.api.interaction_api import InteractionApi
from openapi_client.api.license_api import LicenseApi
from openapi_client.api.like_api import LikeApi
from openapi_client.api.location_api import LocationApi
from openapi_client.api.media_api import MediaApi
from openapi_client.api.mediatype_api import MediatypeApi
from openapi_client.api.memorizedreport_api import MemorizedreportApi
from openapi_client.api.menu_api import MenuApi
from openapi_client.api.my_api import MyApi
from openapi_client.api.notification_api import NotificationApi
from openapi_client.api.notificationtopic_api import NotificationtopicApi
from openapi_client.api.push_api import PushApi
from openapi_client.api.qrlabels_api import QrlabelsApi
from openapi_client.api.qrlogin_api import QrloginApi
from openapi_client.api.quickpanel_api import QuickpanelApi
from openapi_client.api.rating_api import RatingApi
from openapi_client.api.report_api import ReportApi
from openapi_client.api.reportschedule_api import ReportscheduleApi
from openapi_client.api.riskmodel_api import RiskmodelApi
from openapi_client.api.role_api import RoleApi
from openapi_client.api.rule_api import RuleApi
from openapi_client.api.schedule_api import ScheduleApi
from openapi_client.api.scheduleintegration_api import ScheduleintegrationApi
from openapi_client.api.search_api import SearchApi
from openapi_client.api.security_api import SecurityApi
from openapi_client.api.seminar_api import SeminarApi
from openapi_client.api.service_api import ServiceApi
from openapi_client.api.serviceassignment_api import ServiceassignmentApi
from openapi_client.api.session_api import SessionApi
from openapi_client.api.sessionattendancelog_api import SessionattendancelogApi
from openapi_client.api.sessionreg_api import SessionregApi
from openapi_client.api.sessionswipe_api import SessionswipeApi
from openapi_client.api.setting_api import SettingApi
from openapi_client.api.social_api import SocialApi
from openapi_client.api.socialgroup_api import SocialgroupApi
from openapi_client.api.sso_api import SsoApi
from openapi_client.api.staffavail_api import StaffavailApi
from openapi_client.api.station_api import StationApi
from openapi_client.api.swipe_api import SwipeApi
from openapi_client.api.tag_api import TagApi
from openapi_client.api.template_api import TemplateApi
from openapi_client.api.term_api import TermApi
from openapi_client.api.textcredit_api import TextcreditApi
from openapi_client.api.translation_api import TranslationApi
from openapi_client.api.user_api import UserApi
from openapi_client.api.usergroup_api import UsergroupApi
from openapi_client.api.userprofile_api import UserprofileApi
from openapi_client.api.usersettings_api import UsersettingsApi
from openapi_client.api.virtualline_api import VirtuallineApi
from openapi_client.api.waitingline_api import WaitinglineApi
