export * from './actionassignmentApi';
import { ActionassignmentApi } from './actionassignmentApi';
export * from './actionitemApi';
import { ActionitemApi } from './actionitemApi';
export * from './actionlogApi';
import { ActionlogApi } from './actionlogApi';
export * from './actionpackApi';
import { ActionpackApi } from './actionpackApi';
export * from './actiontypeApi';
import { ActiontypeApi } from './actiontypeApi';
export * from './adhocqueryApi';
import { AdhocqueryApi } from './adhocqueryApi';
export * from './adhocreportsApi';
import { AdhocreportsApi } from './adhocreportsApi';
export * from './advancedstationApi';
import { AdvancedstationApi } from './advancedstationApi';
export * from './advroleApi';
import { AdvroleApi } from './advroleApi';
export * from './advrolesApi';
import { AdvrolesApi } from './advrolesApi';
export * from './appointmentApi';
import { AppointmentApi } from './appointmentApi';
export * from './appshareApi';
import { AppshareApi } from './appshareApi';
export * from './attendancelogApi';
import { AttendancelogApi } from './attendancelogApi';
export * from './attendancelogcommentApi';
import { AttendancelogcommentApi } from './attendancelogcommentApi';
export * from './attendancerestrictionApi';
import { AttendancerestrictionApi } from './attendancerestrictionApi';
export * from './beaconApi';
import { BeaconApi } from './beaconApi';
export * from './bgjobApi';
import { BgjobApi } from './bgjobApi';
export * from './captchaApi';
import { CaptchaApi } from './captchaApi';
export * from './clientApi';
import { ClientApi } from './clientApi';
export * from './communityApi';
import { CommunityApi } from './communityApi';
export * from './compasscategoryApi';
import { CompasscategoryApi } from './compasscategoryApi';
export * from './compassserviceApi';
import { CompassserviceApi } from './compassserviceApi';
export * from './computerlabApi';
import { ComputerlabApi } from './computerlabApi';
export * from './deadendrecordingApi';
import { DeadendrecordingApi } from './deadendrecordingApi';
export * from './departmentApi';
import { DepartmentApi } from './departmentApi';
export * from './easyloginApi';
import { EasyloginApi } from './easyloginApi';
export * from './eventApi';
import { EventApi } from './eventApi';
export * from './eventregApi';
import { EventregApi } from './eventregApi';
export * from './exportApi';
import { ExportApi } from './exportApi';
export * from './featureApi';
import { FeatureApi } from './featureApi';
export * from './generalApi';
import { GeneralApi } from './generalApi';
export * from './holidayApi';
import { HolidayApi } from './holidayApi';
export * from './importApi';
import { ImportApi } from './importApi';
export * from './interactionApi';
import { InteractionApi } from './interactionApi';
export * from './licenseApi';
import { LicenseApi } from './licenseApi';
export * from './likeApi';
import { LikeApi } from './likeApi';
export * from './locationApi';
import { LocationApi } from './locationApi';
export * from './mediaApi';
import { MediaApi } from './mediaApi';
export * from './mediatypeApi';
import { MediatypeApi } from './mediatypeApi';
export * from './memorizedreportApi';
import { MemorizedreportApi } from './memorizedreportApi';
export * from './menuApi';
import { MenuApi } from './menuApi';
export * from './myApi';
import { MyApi } from './myApi';
export * from './notificationApi';
import { NotificationApi } from './notificationApi';
export * from './notificationtopicApi';
import { NotificationtopicApi } from './notificationtopicApi';
export * from './pushApi';
import { PushApi } from './pushApi';
export * from './qrlabelsApi';
import { QrlabelsApi } from './qrlabelsApi';
export * from './qrloginApi';
import { QrloginApi } from './qrloginApi';
export * from './quickpanelApi';
import { QuickpanelApi } from './quickpanelApi';
export * from './ratingApi';
import { RatingApi } from './ratingApi';
export * from './reportApi';
import { ReportApi } from './reportApi';
export * from './reportscheduleApi';
import { ReportscheduleApi } from './reportscheduleApi';
export * from './riskmodelApi';
import { RiskmodelApi } from './riskmodelApi';
export * from './roleApi';
import { RoleApi } from './roleApi';
export * from './ruleApi';
import { RuleApi } from './ruleApi';
export * from './scheduleApi';
import { ScheduleApi } from './scheduleApi';
export * from './scheduleintegrationApi';
import { ScheduleintegrationApi } from './scheduleintegrationApi';
export * from './searchApi';
import { SearchApi } from './searchApi';
export * from './securityApi';
import { SecurityApi } from './securityApi';
export * from './seminarApi';
import { SeminarApi } from './seminarApi';
export * from './serviceApi';
import { ServiceApi } from './serviceApi';
export * from './serviceassignmentApi';
import { ServiceassignmentApi } from './serviceassignmentApi';
export * from './sessionApi';
import { SessionApi } from './sessionApi';
export * from './sessionattendancelogApi';
import { SessionattendancelogApi } from './sessionattendancelogApi';
export * from './sessionregApi';
import { SessionregApi } from './sessionregApi';
export * from './sessionswipeApi';
import { SessionswipeApi } from './sessionswipeApi';
export * from './settingApi';
import { SettingApi } from './settingApi';
export * from './socialApi';
import { SocialApi } from './socialApi';
export * from './socialgroupApi';
import { SocialgroupApi } from './socialgroupApi';
export * from './ssoApi';
import { SsoApi } from './ssoApi';
export * from './staffavailApi';
import { StaffavailApi } from './staffavailApi';
export * from './stationApi';
import { StationApi } from './stationApi';
export * from './swipeApi';
import { SwipeApi } from './swipeApi';
export * from './tagApi';
import { TagApi } from './tagApi';
export * from './templateApi';
import { TemplateApi } from './templateApi';
export * from './termApi';
import { TermApi } from './termApi';
export * from './textcreditApi';
import { TextcreditApi } from './textcreditApi';
export * from './translationApi';
import { TranslationApi } from './translationApi';
export * from './userApi';
import { UserApi } from './userApi';
export * from './usergroupApi';
import { UsergroupApi } from './usergroupApi';
export * from './userprofileApi';
import { UserprofileApi } from './userprofileApi';
export * from './usersettingsApi';
import { UsersettingsApi } from './usersettingsApi';
export * from './virtuallineApi';
import { VirtuallineApi } from './virtuallineApi';
export * from './waitinglineApi';
import { WaitinglineApi } from './waitinglineApi';
import * as fs from 'fs';
import * as http from 'http';

export class HttpError extends Error {
    constructor (public response: http.ClientResponse, public body: any, public statusCode?: number) {
        super('HTTP request failed');
        this.name = 'HttpError';
    }
}

export interface RequestDetailedFile {
    value: Buffer;
    options?: {
        filename?: string;
        contentType?: string;
    }
}

export type RequestFile = string | Buffer | fs.ReadStream | RequestDetailedFile;

export const APIS = [ActionassignmentApi, ActionitemApi, ActionlogApi, ActionpackApi, ActiontypeApi, AdhocqueryApi, AdhocreportsApi, AdvancedstationApi, AdvroleApi, AdvrolesApi, AppointmentApi, AppshareApi, AttendancelogApi, AttendancelogcommentApi, AttendancerestrictionApi, BeaconApi, BgjobApi, CaptchaApi, ClientApi, CommunityApi, CompasscategoryApi, CompassserviceApi, ComputerlabApi, DeadendrecordingApi, DepartmentApi, EasyloginApi, EventApi, EventregApi, ExportApi, FeatureApi, GeneralApi, HolidayApi, ImportApi, InteractionApi, LicenseApi, LikeApi, LocationApi, MediaApi, MediatypeApi, MemorizedreportApi, MenuApi, MyApi, NotificationApi, NotificationtopicApi, PushApi, QrlabelsApi, QrloginApi, QuickpanelApi, RatingApi, ReportApi, ReportscheduleApi, RiskmodelApi, RoleApi, RuleApi, ScheduleApi, ScheduleintegrationApi, SearchApi, SecurityApi, SeminarApi, ServiceApi, ServiceassignmentApi, SessionApi, SessionattendancelogApi, SessionregApi, SessionswipeApi, SettingApi, SocialApi, SocialgroupApi, SsoApi, StaffavailApi, StationApi, SwipeApi, TagApi, TemplateApi, TermApi, TextcreditApi, TranslationApi, UserApi, UsergroupApi, UserprofileApi, UsersettingsApi, VirtuallineApi, WaitinglineApi];
