# coding: utf-8

"""
    AccuCampus OpenAPI 3

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.media_api import MediaApi  # noqa: E501
from openapi_client.rest import ApiException


class TestMediaApi(unittest.TestCase):
    """MediaApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.media_api.MediaApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_media_checkin(self):
        """Test case for media_checkin

        Check in media item  # noqa: E501
        """
        pass

    def test_media_checkout(self):
        """Test case for media_checkout

        Check out media item  # noqa: E501
        """
        pass

    def test_media_checkoutlist(self):
        """Test case for media_checkoutlist

        View a list of past media checkouts  # noqa: E501
        """
        pass

    def test_media_delete(self):
        """Test case for media_delete

        Delete a media item  # noqa: E501
        """
        pass

    def test_media_deletecheckoutlog(self):
        """Test case for media_deletecheckoutlog

        Delete a media checkout log  # noqa: E501
        """
        pass

    def test_media_get(self):
        """Test case for media_get

        Search and view details of a media item  # noqa: E501
        """
        pass

    def test_media_getbycode(self):
        """Test case for media_getbycode

        Search media item by unique code  # noqa: E501
        """
        pass

    def test_media_getcheckout(self):
        """Test case for media_getcheckout

        View details of a media item checkout information  # noqa: E501
        """
        pass

    def test_media_getcheckoutlog(self):
        """Test case for media_getcheckoutlog

        View details of a media checkout log  # noqa: E501
        """
        pass

    def test_media_list(self):
        """Test case for media_list

        View a list of media items  # noqa: E501
        """
        pass

    def test_media_save(self):
        """Test case for media_save

        Create or edit a media item  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
