# coding: utf-8

"""
    AccuCampus OpenAPI 3

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.riskmodel_api import RiskmodelApi  # noqa: E501
from openapi_client.rest import ApiException


class TestRiskmodelApi(unittest.TestCase):
    """RiskmodelApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.riskmodel_api.RiskmodelApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_riskmodel_checkanalysis(self):
        """Test case for riskmodel_checkanalysis

        Check the status of the analysis of a specified risk assessment model  # noqa: E501
        """
        pass

    def test_riskmodel_delete(self):
        """Test case for riskmodel_delete

        Delete a risk assessment model  # noqa: E501
        """
        pass

    def test_riskmodel_get(self):
        """Test case for riskmodel_get

        View details of a risk assessment model  # noqa: E501
        """
        pass

    def test_riskmodel_getscore(self):
        """Test case for riskmodel_getscore

        View the risk score for a specific user  # noqa: E501
        """
        pass

    def test_riskmodel_list(self):
        """Test case for riskmodel_list

        View a list of risk assessment models  # noqa: E501
        """
        pass

    def test_riskmodel_predict(self):
        """Test case for riskmodel_predict

        Predict risk based on an assessment model  # noqa: E501
        """
        pass

    def test_riskmodel_process(self):
        """Test case for riskmodel_process

        Process a risk assessment model  # noqa: E501
        """
        pass

    def test_riskmodel_refresh(self):
        """Test case for riskmodel_refresh

        Refresh the information used in a risk assessment model  # noqa: E501
        """
        pass

    def test_riskmodel_save(self):
        """Test case for riskmodel_save

        Create or edit a risk assessment model  # noqa: E501
        """
        pass

    def test_riskmodel_termprecedences(self):
        """Test case for riskmodel_termprecedences

        View all default term precedences  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
