=begin
#AccuClub OpenAPI 3

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::CaptchaApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CaptchaApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::CaptchaApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CaptchaApi' do
    it 'should create an instance of CaptchaApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::CaptchaApi)
    end
  end

  # unit tests for captcha_getchallenge
  # Gets a captcha challenge that the user must complete to do certain requests.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'captcha_getchallenge test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for captcha_getimage
  # Gets a captcha image that the user must complete to do certain requests.
  # @param captchatoken The captcha token or ID returned by the captcha.getchallenge action
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'captcha_getimage test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
